# This workflow run test suite on every dependency changes

name: Test suite

on:
  push:
    branches: [ main ]
    paths:
      - package.json

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build
    - run: npm test
